# Generated by Django 4.1.5 on 2023-02-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_watchlisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='creation_date',
        ),
    ]
